"""new fields in user model

Revision ID: 925d96c8dea8
Revises: 338d40b4f632
Create Date: 2020-02-13 10:49:12.063163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925d96c8dea8'
down_revision = '338d40b4f632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
